# Change these first
owner: tmkhiem # Your GitHub organization or username, where this repository lives
repo: hcmus-web-uptime # The name of this repository

sites:
  - name: Homepage
    url: https://hcmus.edu.vn/
  - name: Portal
    url: https://portal.hcmus.edu.vn/
  - name: Portal 1
    url: https://portal1.hcmus.edu.vn/
  - name: Portal 2
    url: https://portal2.hcmus.edu.vn/
  - name: Portal 3
    url: https://portal3.hcmus.edu.vn/
  - name: Portal 4
    url: https://portal4.hcmus.edu.vn/
  - name: Portal 5
    url: https://portal5.hcmus.edu.vn/
  - name: Portal 6
    url: https://portal6.hcmus.edu.vn/
  - name: HR
    url: https://hr.hcmus.edu.vn/
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /hcmums-web-uptime
  logoUrl: http://www.chemistry.hcmus.edu.vn/images/logo%20KHTN_REMAKE%201.png
  name: HCMUS Web uptime
  introTitle: "HCMUS web status"
  introMessage: HCMUS web status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
